### ISSUE TITLE
Exporting functions

### ISSUE THREAD

**Issue by matthewdking** [fac-13/phac-kpnet-autocomplete#56]
```js
const handlers = (module.exports = {});
```
I would advise creating functions using `const notFound = (req, res) => {}` syntax. This can then be exported at the end of the file.

```js
module.exports = { serverLanding, serverPublic, serverSearchApi, pageNotFound }
```

**Comment by Parissai** [comment]
@matthewdking We wrote this way because of [our code along workshop solution](https://github.com/foundersandcoders/Node-Intro-Workshop/blob/completed-workshop/src/handlers/handlers.js). We thought since we could export at the same time as we write the functions, we could be sure it is exported and we haven't forgotten any of the functions. I was wondering why it is not considered *best practice*?!

**Comment by matthewdking** [comment]
Sorry, I hadn't seen that in the code along solution.

The use of `const` stops you from reasssigning functions.
`something = somethingelse = anotherthing` is confusing
